### ISSUE TITLE
Mapeo Git.

### ISSUE THREAD

**Issue by MrCodemancer** [CGHV-UTU/Proyecto2024#65]
### Falta información para saber qué exactamente hay que hacer.

El "mapeo Git" se refiere al proceso o la acción de asignar o vincular un repositorio remoto de Git a uno local en tu máquina. En Git, un repositorio remoto es una copia de tu repositorio local que se encuentra en otro lugar, como en un servidor en la nube o en otro equipo. El mapeo Git implica establecer una conexión entre tu repositorio local y el repositorio remoto para que puedas sincronizar cambios entre ellos.

Este proceso generalmente implica configurar una URL remota para el repositorio y definir cómo se manejarán las ramas y los cambios entre el repositorio local y el remoto. Algunas de las operaciones comunes que se realizan con el mapeo Git incluyen clonar un repositorio remoto para obtener una copia local, agregar un repositorio remoto a un repositorio local existente y realizar operaciones de empuje (push) y tirado (pull) para sincronizar los cambios entre el repositorio local y el remoto.

Video sobre el mapeo de objetos GIT
https://www.youtube.com/watch?v=uQQ5GITSJms&ab_channel=SantiLopezWeb

# Actualización

Es sólo marcar las tareas (o issues) como completadas

**Comment by MaximoCastro191** [comment]
El mapeo en Git se refiere a la forma en que los archivos y las carpetas en tu sistema de archivos se corresponden con los objetos en un repositorio de Git. Esto incluye cómo los cambios en estos archivos y carpetas se registran y gestionan mediante Git
